In [1]:
import torch

In [2]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [4]:
i = torch.ones((5, 3), dtype= torch.int16)
print(i)
print(i.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
torch.int16


In [16]:
torch.manual_seed(1729)
r1 = torch.rand(2,2)
# print('A random tensor: \n ', r1)
print('A random tensor: ')
print(r1)

r2 = torch.rand(2,2)
print('\nA Different random tensor:')
print(r2) #new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print('\nShould match r1:')
print(r3)

A random tensor: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A Different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
